{% set name = "grpc-stubs" %}
{% set version = "1.53.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 70a0840747bd73c2c82fe819699bbf4fcf6d59bd0ed27a4713a240e0c697e1ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - grpcio
    - mypy >=0.730
    - python >={{ python_min }}
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
  commands:
    # grpc-stubs doesn't include py.typed
    # https://www.python.org/dev/peps/pep-0561/#stub-only-packages
    - test -f $SP_DIR/grpc-stubs/__init__.pyi  # [unix]
    - test -f $SP_DIR/grpc_channelz-stubs/__init__.pyi  # [unix]
    - test -f $SP_DIR/grpc_health-stubs/__init__.pyi  # [unix]
    - test -f $SP_DIR/grpc_reflection-stubs/__init__.pyi  # [unix]
    - test -f $SP_DIR/grpc_status-stubs/__init__.pyi  # [unix]

    - if not exist %SP_DIR%\\grpc-stubs\\__init__.pyi exit  # [win]
    - if not exist %SP_DIR%\\grpc_channelz-stubs\\__init__.pyi exit  # [win]
    - if not exist %SP_DIR%\\grpc_health-stubs\\__init__.pyi exit  # [win]
    - if not exist %SP_DIR%\\grpc_reflection-stubs\\__init__.pyi exit  # [win]
    - if not exist %SP_DIR%\\grpc_status-stubs\\__init__.pyi exit  # [win]

about:
  home: https://github.com/shabbyrobe/grpc-stubs
  summary: Mypy stubs for gRPC
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
