{% set name = "grpc-stubs" %}
{% set version = "1.24.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpc-stubs-{{ version }}.tar.gz
  sha256: 0d64f8acc5c5d4910db97b78f070a8bef5dc72e9618547b6a0850ed49e41ef7a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - grpcio
    - mypy >=0.730
    - python >=3.6
    - typing-extensions

test:
  commands:
    # grpc-stubs doesn't include py.typed
    # https://www.python.org/dev/peps/pep-0561/#stub-only-packages
    - test -f $SP_DIR/grpc-stubs/__init__.pyi  # [unix]
    - test -f $SP_DIR/grpc_channelz-stubs/__init__.pyi  # [unix]
    - test -f $SP_DIR/grpc_health-stubs/__init__.pyi  # [unix]
    - test -f $SP_DIR/grpc_reflection-stubs/__init__.pyi  # [unix]
    - test -f $SP_DIR/grpc_status-stubs/__init__.pyi  # [unix]

    - if not exist %SP_DIR%\\grpc-stubs\\__init__.pyi exit  # [win]
    - if not exist %SP_DIR%\\grpc_channelz-stubs\\__init__.pyi exit  # [win]
    - if not exist %SP_DIR%\\grpc_health-stubs\\__init__.pyi exit  # [win]
    - if not exist %SP_DIR%\\grpc_reflection-stubs\\__init__.pyi exit  # [win]
    - if not exist %SP_DIR%\\grpc_status-stubs\\__init__.pyi exit  # [win]

about:
  home: https://github.com/shabbyrobe/grpc-stubs
  summary: Mypy stubs for gRPC
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
